on: [push]

name: CI

jobs:
  build_and_test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: "Install Bikeshed"
        run: "pip3 install bikeshed"
      - name: "Build docs"
        run: "make"
#      - name: "Assert docs/ is up to date"
#        run: "git diff-files --quiet -- docs"
